[package]
name = "hyper-rustls"
version = "0.22.1"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
log = "0.4.4"
ct-logs = { version = "^0.8", optional = true }
hyper = { version = "0.14", default-features = false, features = ["client", "http1"] }
rustls = "0.19"
rustls-native-certs = { version = "0.5.0", optional = true }
tokio = "1.0"
tokio-rustls = "0.22"
webpki = "0.21.0"
webpki-roots = { version = "0.21", optional = true }

[dev-dependencies]
async-stream = "0.3.0"
tokio = { version = "1.0", features = ["io-std", "macros", "net", "rt-multi-thread"] }
hyper = { version = "0.14", features = ["full"] }
futures-util = { version = "0.3.1", default-features = false }

[features]
default = ["native-tokio", "http1"]
http1 = ["hyper/http1"]
http2 = ["hyper/http2"]
webpki-tokio = ["tokio-runtime", "webpki-roots"]
native-tokio = ["tokio-runtime", "rustls-native-certs"]
tokio-runtime =  ["hyper/runtime", "ct-logs"]

[[example]]
name = "client"
path = "examples/client.rs"
required-features = ["native-tokio", "tokio-runtime"]

[[example]]
name = "server"
path = "examples/server.rs"
required-features = ["tokio-runtime"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
