[package]
name = "hyper-rustls"
version = "0.13.0"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
ct-logs = "0.3"
futures = "0.1.21"
http = "0.1"
hyper = "0.12"
rustls = "0.12"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-reactor = "0.1.2"
tokio-rustls = "0.6"
tokio-tcp = "0.1"
webpki = "0.18.0-alpha"
webpki-roots = "0.14"
