[package]
name = "hyper-rustls"
version = "0.15.1"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
description = "Rustls+hyper integration for pure rust HTTPS"
homepage = "https://github.com/ctz/hyper-rustls"
repository = "https://github.com/ctz/hyper-rustls"

[dependencies]
bytes = "0.4"
ct-logs = "0.5"
futures = "0.1.21"
http = "0.1"
hyper = "0.12.14"
rustls = "0.15"
tokio-io = "0.1.1"
tokio-rustls = "0.8"
tokio-tcp = "0.1"
webpki = "0.19.0"
webpki-roots = "0.16"

[dev-dependencies]
tokio = "0.1"

[patch.crates-io]
tokio-rustls = { git = "https://github.com/ctz/tokio-rustls.git" }
